language: ruby
cache: bundler
bundler_args: --without production
rvm:
  - 2.1.6
  - 2.2.0
  - 2.2.1
  - 2.2.2
  - 2.2.3
gemfile:
  - Gemfile
  - Gemfile-rails
  - Gemfile-minimum
before_install: gem install bundler -v 1.10.6
addons:
  code_climate:
    repo_token: f1d3de8fd8a6342cd1a107dd7619a218e433a338b4138a4dc3d0fb4a27060086
